In [1]:
import tensorflow as tf
import numpy as np

/home/administrator/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


In [2]:
tf.reset_default_graph()

In [308]:
X = tf.placeholder(tf.float32,shape = [None,10,200])

In [347]:
x = np.random.normal(0,0.8,[3,10,200]).astype(np.float32)
batch_size = 3

** Can change up the activation functions later if softmax blows upto inf or goes down to zero or something**

** If the input is distributed around zero it performs better ** 

** Matmul works in a good way in 3D too same as 2D**

** Bias vector size keep the same as each row size, it then adds to every row of the vector you want to add it to**

In [376]:
def neural_network(combined_BiRnn_output):
    
    Wx1 = tf.Variable(tf.random_normal([batch_size,200,50],0.3,1/200))
    Wx2 = tf.Variable(tf.random_normal([batch_size,50,1],0.5,1/50))
    b1 = tf.Variable(tf.constant(0.5,shape = [50]))
    b2 = tf.Variable(tf.constant(0.3,shape = [1]))
    first_out = tf.nn.tanh(tf.add(tf.matmul(combined_BiRnn_output,Wx1),b1))
    e = tf.nn.relu(tf.add(tf.matmul(first_out,Wx2),b2))
        
    return e

In [430]:
def softmax(e_values):
    j = tf.exp(e_values)
    totals = tf.reduce_sum(tf.exp(e_values),1)
    j = tf.unstack(j,axis = 0)
    totals = tf.unstack(totals, axis = 0)
    for i in range(batch_size):
        j[i] = j[i]/totals[i]
    j = tf.stack(j,axis = 0)
    return j

In [366]:
a = tf.constant([[[1,2,3],[2,3,1],[4,5,2],[2,1,1]],[[0,2,3],[4,5,0],[7,3,1],[4,1,2]],[[1,1,1],[0,1,1],[3,2,4],[4,3,0]]])
b = tf.constant([[[1,1,1],[1,1,1],[1,1,1]],[[2,2,2],[2,2,2],[2,2,2]],[[3,3,3],[3,3,3],[3,3,3]]])
c = tf.constant([1,1,1])

In [371]:
d = tf.add(a,c)
e = tf.add(b,c)

In [431]:
e = neural_network(X)
f = softmax(e)

In [432]:
init = tf.global_variables_initializer()

In [433]:
with tf.Session() as sess:
    sess.run(init)
    k = sess.run(f , feed_dict = {X:x})

[array([0.99999994], dtype=float32),
 array([1.], dtype=float32),
 array([1.], dtype=float32)]

In [415]:
l

array([[[1, 2, 3],
        [2, 3, 1],
        [4, 5, 2],
        [2, 1, 1]],

       [[0, 2, 3],
        [4, 5, 0],
        [7, 3, 1],
        [4, 1, 2]],

       [[1, 1, 1],
        [0, 1, 1],
        [3, 2, 4],
        [4, 3, 0]]], dtype=int32)

In [19]:
tf.reduce_sum?

In [302]:
tf.matmul?

## Weighted average of alpha values and 200 dim output of BiRnn

In [1]:
import tensorflow as tf
import numpy as np

/home/administrator/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


In [30]:
# outs = np.random.normal(1,1,[3,850,200]).astype(np.float32)
# alpha = np.random.normal(1,1,[3,850,1]).astype(np.float32)

outs = np.array([[[1,2,3],[2,3,1],[4,5,2],[2,1,1]],[[0,2,3],[4,5,2],[7,3,1],[4,1,2]],[[1,1,1],[0,1,1],[3,2,4],[4,3,0]]])
alpha = np.array([1,2,2,3,2,3,4,5,5,6,7,8]).reshape(3,4,1)

In [32]:
def weighted_average(outs,alpha):
    weighted_average = outs*alpha
    return weighted_average

In [31]:
A = tf.placeholder(tf.float32,[3,4,3])
B = tf.placeholder(tf.float32,[3,4,1])

In [33]:
c = weighted_average(A,B)
d = tf.reduce_sum(c,axis = 1)

In [34]:
with tf.Session() as sess:
    e = sess.run(d, feed_dict = {A:outs,B:alpha})

### There is not a single alpha for a word , giving importance to that word, there will be more alpha values for each word , as many alpha's as output words. 
### So for the first word of  output , the first word of input has alpha1 importance, for the second word it has alpha2 importance etc.

In [1]:
import tensorflow as tf
import numpy as np

/home/administrator/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


In [2]:
num_outputs = 30

In [79]:
outs = np.random.normal(1,1,[3,850,200]).astype(np.float32)
alpha = np.random.normal(1,1,[3,850,1]).astype(np.float32)

# outs = np.array([[[1,2,3],[2,3,1],[4,5,2],[2,1,1]],[[0,2,3],[4,5,2],[7,3,1],[4,1,2]],[[1,1,1],[0,1,1],[3,2,4],[4,3,0]]])
# alpha = np.array([1,2,2,3,2,3,4,5,5,6,7,8]).reshape(3,4,1)

# j = tf.constant([[9,12,14,16],[3,8,7,2],[4,5,3,4],[6,6,7,9],[3,2,8,11],[1,16,13,12],[0,9,12,3]])
# total = tf.constant([26,58,64,57])

In [4]:
X = tf.placeholder(tf.float32, shape = [None,850,200])

In [5]:
batch_size = 3

In [48]:
def neural_network(combined_BiRnn_output):
    
    Wx1 = tf.Variable(tf.random_normal([batch_size,200,100],0.3,1/200))
    Wx2 = tf.Variable(tf.random_normal([batch_size,100,num_outputs],0.5,1/50))
    b1 = tf.Variable(tf.constant(0.5,shape = [100]))
    b2 = tf.Variable(tf.constant(0.3,shape = [num_outputs]))
    first_out = tf.nn.tanh(tf.add(tf.matmul(combined_BiRnn_output,Wx1),b1))
    e = tf.nn.relu(tf.add(tf.matmul(first_out,Wx2),b2))
        
    return e

In [17]:
def softmax(e_values):
    j = tf.exp(e_values)
    totals = tf.reduce_sum(j,1)
    j = tf.unstack(j,axis = 0)
    totals = tf.unstack(totals, axis = 0)
    for i in range(batch_size):
        j[i] = j[i]/totals[i]
    j = tf.stack(j,axis = 0)
    return j

In [80]:
e = neural_network(X)
f = softmax(e)

In [81]:
init = tf.global_variables_initializer()

In [82]:
with tf.Session() as sess:
    sess.run(init)
    
    g = sess.run(f,feed_dict = {X : outs})

## Weighted Sum 

In [3]:
import tensorflow as tf
import numpy as np

In [37]:
outputs = tf.constant([[[1,2,1,3,4,5],[2,1,3,4,3,2],[1,1,6,7,8,3],[4,5,9,9,3,2]],[[1,2,1,3,4,5],[2,1,3,4,3,2],[1,1,6,7,8,3],[4,5,9,9,3,2]]])
alphas = tf.constant(g)

In [26]:
e = tf.transpose(alphas,perm=[0,2,1])

In [30]:
init = tf.global_variables_initializer()
with tf.Session() as sess:
    sess.run(init)
    f = sess.run(alphas)
    g = sess.run(e)

In [24]:
np.transpose(alphas,axes = [0,2,1])

array([[[1, 1],
        [1, 0],
        [3, 1],
        [1, 5]],

       [[1, 1],
        [1, 0],
        [3, 1],
        [1, 5]]])

In [31]:
f

array([[[1, 1, 3, 1],
        [1, 0, 1, 5]],

       [[1, 1, 3, 1],
        [1, 0, 1, 5]]], dtype=int32)

In [32]:
g

array([[[1, 1],
        [1, 0],
        [3, 1],
        [1, 5]],

       [[1, 1],
        [1, 0],
        [3, 1],
        [1, 5]]], dtype=int32)

In [38]:
e = tf.matmul(tf.transpose(alphas,perm = [0,2,1]),outputs)

In [39]:
init = tf.global_variables_initializer()
with tf.Session() as sess:
    sess.run(init)
    f = sess.run(e)

In [40]:
f

array([[[10, 11, 31, 37, 34, 18],
        [22, 28, 52, 55, 27, 18]],

       [[10, 11, 31, 37, 34, 18],
        [22, 28, 52, 55, 27, 18]]], dtype=int32)

In [41]:
def weighted_average(outputs,alphas):
    
    alphas = tf.transpose(alphas,perm = [0,2,1])
    context_vectors = tf.matmul(alphas,outputs)
    
    return context_vectors

In [43]:
e = weighted_average(outputs,alphas)
init = tf.global_variables_initializer()
with tf.Session() as sess:
    sess.run(init)
    f = sess.run(e)

In [44]:
f

array([[[10, 11, 31, 37, 34, 18],
        [22, 28, 52, 55, 27, 18]],

       [[10, 11, 31, 37, 34, 18],
        [22, 28, 52, 55, 27, 18]]], dtype=int32)

## Decoder Network code 

In [1]:
import tensorflow as tf
import numpy as np

/home/administrator/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


In [10]:
rnn_cell_dimension = 200
batch_size = 3
num_output_steps = 84
context_vector = np.random.normal(2,3,size = [batch_size,num_output_steps,rnn_cell_dimension])

In [4]:
context = tf.placeholder(tf.float32,shape = [batch_size,num_output_steps,rnn_cell_dimension])

###  Not doing sequence length here do that later and see 

In [7]:
cell_factory = tf.nn.rnn_cell.LSTMCell(100,activation=tf.nn.relu)
initial_state = cell_factory.zero_state(batch_size, dtype=tf.float32)
decoder, _ = tf.nn.dynamic_rnn(cell_factory,context,initial_state=initial_state)

In [11]:
init = tf.global_variables_initializer()
with tf.Session() as sess:
    sess.run(init)
    
    e = sess.run(decoder,feed_dict = {context : context_vector})

In [13]:
e.shape

(3, 84, 100)

In [18]:
def output_neural_network(decoder_rnn):
    
    Wx1 = tf.Variable(tf.random_normal([batch_size,100,200000],0.5,1/num_output_steps))
    b1 = tf.Variable(tf.constant(0.5,shape = [200000]))
    first_out = tf.nn.softmax(tf.nn.relu((tf.add(tf.matmul(decoder_rnn,Wx1),b1))))
        
    return first_out

In [19]:
e = output_neural_network(decoder)

In [20]:
init = tf.global_variables_initializer()
with tf.Session() as sess:
    sess.run(init)
    
    f = sess.run(e,feed_dict = {context : context_vector})

In [29]:
c_e = tf.nn.softmax_cross_entropy_with_logits_v2(logits = probability_distribution,labels = batch_y)
optimizer = tf.train.AdamOptimizer(learning_rate = 0.3)
train = optimizer.minimize(c_e)

NameError: name 'probability_distribution' is not defined