In [1]:
import tensorflow as tf
import numpy as np

/home/administrator/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


In [2]:
tf.reset_default_graph()

In [308]:
X = tf.placeholder(tf.float32,shape = [None,10,200])

In [347]:
x = np.random.normal(0,0.8,[3,10,200]).astype(np.float32)
batch_size = 3

** Can change up the activation functions later if softmax blows upto inf or goes down to zero or something**

** If the input is distributed around zero it performs better ** 

** Matmul works in a good way in 3D too same as 2D**

** Bias vector size keep the same as each row size, it then adds to every row of the vector you want to add it to**

In [376]:
def neural_network(combined_BiRnn_output):
    
    Wx1 = tf.Variable(tf.random_normal([batch_size,200,50],0.3,1/200))
    Wx2 = tf.Variable(tf.random_normal([batch_size,50,1],0.5,1/50))
    b1 = tf.Variable(tf.constant(0.5,shape = [50]))
    b2 = tf.Variable(tf.constant(0.3,shape = [1]))
    first_out = tf.nn.tanh(tf.add(tf.matmul(combined_BiRnn_output,Wx1),b1))
    e = tf.nn.relu(tf.add(tf.matmul(first_out,Wx2),b2))
        
    return e

In [430]:
def softmax(e_values):
    j = tf.exp(e_values)
    totals = tf.reduce_sum(tf.exp(e_values),1)
    j = tf.unstack(j,axis = 0)
    totals = tf.unstack(totals, axis = 0)
    for i in range(batch_size):
        j[i] = j[i]/totals[i]
    j = tf.stack(j,axis = 0)
    return j

In [366]:
a = tf.constant([[[1,2,3],[2,3,1],[4,5,2],[2,1,1]],[[0,2,3],[4,5,0],[7,3,1],[4,1,2]],[[1,1,1],[0,1,1],[3,2,4],[4,3,0]]])
b = tf.constant([[[1,1,1],[1,1,1],[1,1,1]],[[2,2,2],[2,2,2],[2,2,2]],[[3,3,3],[3,3,3],[3,3,3]]])
c = tf.constant([1,1,1])

In [371]:
d = tf.add(a,c)
e = tf.add(b,c)

In [431]:
e = neural_network(X)
f = softmax(e)

In [432]:
init = tf.global_variables_initializer()

In [433]:
with tf.Session() as sess:
    sess.run(init)
    k = sess.run(f , feed_dict = {X:x})

[array([0.99999994], dtype=float32),
 array([1.], dtype=float32),
 array([1.], dtype=float32)]

In [415]:
l

array([[[1, 2, 3],
        [2, 3, 1],
        [4, 5, 2],
        [2, 1, 1]],

       [[0, 2, 3],
        [4, 5, 0],
        [7, 3, 1],
        [4, 1, 2]],

       [[1, 1, 1],
        [0, 1, 1],
        [3, 2, 4],
        [4, 3, 0]]], dtype=int32)

In [19]:
tf.reduce_sum?

In [302]:
tf.matmul?

## Weighted average of alpha values and 200 dim output of BiRnn

In [1]:
import tensorflow as tf
import numpy as np

/home/administrator/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


In [30]:
# outs = np.random.normal(1,1,[3,850,200]).astype(np.float32)
# alpha = np.random.normal(1,1,[3,850,1]).astype(np.float32)

outs = np.array([[[1,2,3],[2,3,1],[4,5,2],[2,1,1]],[[0,2,3],[4,5,2],[7,3,1],[4,1,2]],[[1,1,1],[0,1,1],[3,2,4],[4,3,0]]])
alpha = np.array([1,2,2,3,2,3,4,5,5,6,7,8]).reshape(3,4,1)

In [32]:
def weighted_average(outs,alpha):
    weighted_average = outs*alpha
    return weighted_average

In [31]:
A = tf.placeholder(tf.float32,[3,4,3])
B = tf.placeholder(tf.float32,[3,4,1])

In [33]:
c = weighted_average(A,B)
d = tf.reduce_sum(c,axis = 1)

In [34]:
with tf.Session() as sess:
    e = sess.run(d, feed_dict = {A:outs,B:alpha})

### There is not a single alpha for a word , giving importance to that word, there will be more alpha values for each word , as many alpha's as output words. 
### So for the first word of  output , the first word of input has alpha1 importance, for the second word it has alpha2 importance etc.